### DISCUSSION TITLE
Memory issue

### DISCUSSION THREAD

**Discussion by gly123456-phy** [mir-group/nequip#530] [General]
Hello,
I have 1900 structures, and each structure has 40 atoms. Now I requested a single GPU to train the model. It looks like there is a memory issue:
"  return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.67 GiB. GPU 0 has a total capacity of 44.42 GiB of which 614.12 MiB is free. Including non-PyTorch memory, this process has 43.81 GiB memory in use. Of the allocated memory 43.23 GiB is allocated by PyTorch, and 78.05 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
"
I was basically using the same config.yaml as the one provided from ./configs. I had tried reducing batch_size from 5 to 2 but it still didn't work. What other parameters I can try? Or should I use multi GPUs? 

Thanks in advance!

**Comment by cw-tan** [comment]
Hi @gly123456-phy ,

Did you change the batch size for both train and val dataloaders? (e.g. val: https://github.com/mir-group/nequip/blob/60eae375988b07a35b0840eff7db42de076c9a73/configs/tutorial.yaml#L82).

You could consider also using OpenEquivariance acceleration: https://nequip.readthedocs.io/en/latest/guide/accelerations/openequivariance.html, which can help improve memory efficiency. Using `compile_mode: compile` (see https://nequip.readthedocs.io/en/latest/guide/accelerations/pt2_compilation.html) may also give a small boost in memory efficiency, if not just speed.

You could also try making `r_max` smaller, what is the value you are currently using? Besides other hyperparameters, depending on the use case and cost-accuracy tradeoff (`l_max`, `num_features`). 

I'd say try these options first before going to DDP (https://nequip.readthedocs.io/en/latest/guide/accelerations/ddp_training.html)

**Reply by gly123456-phy** [reply]
Hello @cw-tan,
Thanks a lot! I tried decreasing batch_size of training data to 1, and it finally worked. But it was very strange as the training speed was so slow. That didn't make sense as I only increased the total number of structures by three times. After checking the training data, I realized my training data has some format issue, and the lattice part was missing for newly added structures. That might be the root cause of the memory issue. After I fixed it, the memory issue is not a problem at all and the training speed also came back to normal. Sorry it's totally my fault.
